# Study7

In [1]:
import numpy as np

In [4]:
n = 10
L = [i for i in range(n)]

In [5]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
A = []
for e in L:
    A.append(e * 2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
n = 100000

In [13]:
L = np.arange(n)
L

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [19]:
A = np.array([2 * e for e in L])
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [16]:
A = 2*L

In [17]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [20]:
A2 = np.array([2 * e for e in range(10)])
A2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
n=10
L = np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Functions

In [25]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [27]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [29]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [30]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [31]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [32]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [33]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [35]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

### 矩阵运算

In [36]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [38]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [39]:
A + B

array([[10, 11],
       [12, 13]])

In [40]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [41]:
A * B

array([[ 0, 10],
       [20, 30]])

In [43]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [44]:
A ** B

array([[    0,     1],
       [ 1024, 59049]], dtype=int32)

In [45]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [46]:
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [47]:
v = np.array([1, 2])

In [48]:
A

array([[0, 1],
       [2, 3]])

In [49]:
v + A

array([[1, 3],
       [3, 5]])

In [50]:
[v]

[array([1, 2])]

In [51]:
A.shape[0]

2

In [52]:
[v] * A.shape[0]

[array([1, 2]), array([1, 2])]

In [53]:
v

array([1, 2])

In [54]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [57]:
B = v.dot(A)
B

array([4, 7])

In [58]:
v.dot(B)

18

In [59]:
A.T

array([[0, 2],
       [1, 3]])

### 聚合操作

In [61]:
L = np.random.random(100)

In [62]:
L

array([0.09984417, 0.78509291, 0.7261594 , 0.60588425, 0.52036767,
       0.58330203, 0.30642292, 0.74130845, 0.90062972, 0.32397816,
       0.35893391, 0.94557767, 0.78709992, 0.38062392, 0.77332744,
       0.38287111, 0.05566163, 0.06326345, 0.86491349, 0.56168642,
       0.46604755, 0.64392182, 0.28348244, 0.20433463, 0.57273123,
       0.00670207, 0.02823218, 0.11325799, 0.31727865, 0.24252157,
       0.10940037, 0.44928244, 0.37145735, 0.29241094, 0.45241539,
       0.3250705 , 0.98039978, 0.72985399, 0.17958303, 0.77640488,
       0.75982647, 0.6195098 , 0.61207159, 0.28397296, 0.07611   ,
       0.18520877, 0.01634652, 0.20454606, 0.15990101, 0.51629724,
       0.91999745, 0.8200221 , 0.71715984, 0.32450878, 0.45655603,
       0.68181138, 0.35336429, 0.25617537, 0.4569981 , 0.21038252,
       0.70259843, 0.14819924, 0.25525429, 0.66536763, 0.16081009,
       0.79224191, 0.63526197, 0.8465291 , 0.03934967, 0.07949212,
       0.17472722, 0.56969493, 0.60933106, 0.84738959, 0.73013

In [63]:
sum(L)

46.47128197535643

In [64]:
np.sum(L)

46.47128197535644

In [65]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

99.3 ms ± 4.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.07 ms ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [66]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.sum(X)

120

In [69]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [70]:
np.prod(X)

0

In [71]:
np.prod(X+1)

2004189184

In [72]:
np.mean(X)

7.5

In [73]:
np.median(X)

7.5

In [74]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [75]:
np.median(v)

2.0

In [76]:
np.percentile(big_array, q=50)

0.4992952724659445

In [77]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.0411092113971065e-06
0.250061181692431
0.4992952724659445
0.7497461120775177
0.9999997075803058


In [78]:
np.var(big_array)

0.08326803648834015

In [79]:
np.std(big_array)

0.2885620149783061

In [80]:
x = np.random.normal(0, 1, size=1000000)

In [81]:
np.mean(x)

0.00012561045217728827

In [82]:
np.std(x)

0.9989048041329239

### 索引

In [83]:
np.min(x)

-4.771457300488207

In [84]:
np.argmin(x)

342891

In [85]:
x[342891]

-4.771457300488207

In [86]:
np.argmax(x)

193565

### 排序和使用索引

In [88]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
np.random.shuffle(x)
x

array([ 6,  5, 15,  8,  3, 10,  9,  1,  2, 13, 12, 14,  0, 11,  7,  4])

In [90]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
X = np.random.randint(10, size=(4, 4))
X

array([[5, 2, 4, 8],
       [0, 1, 1, 0],
       [6, 8, 4, 1],
       [1, 8, 0, 7]])

In [92]:
np.sort(X)

array([[2, 4, 5, 8],
       [0, 0, 1, 1],
       [1, 4, 6, 8],
       [0, 1, 7, 8]])

In [93]:
np.sort(X, axis=0)

array([[0, 1, 0, 0],
       [1, 2, 1, 1],
       [5, 8, 4, 7],
       [6, 8, 4, 8]])

In [94]:
x

array([ 6,  5, 15,  8,  3, 10,  9,  1,  2, 13, 12, 14,  0, 11,  7,  4])

In [95]:
x.sort()

In [96]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [97]:
np.random.shuffle(x)

In [98]:
x

array([ 0,  1,  5,  6,  9, 14,  3, 10,  4, 12,  7,  2,  8, 15, 11, 13])

In [99]:
np.argsort(x)

array([ 0,  1, 11,  6,  8,  2,  3, 10, 12,  4,  7, 14,  9, 15,  5, 13],
      dtype=int64)

In [100]:
np.partition(x, 3)

array([ 2,  1,  0,  3,  5,  4,  6,  7,  8,  9, 10, 12, 14, 15, 11, 13])

In [101]:
np.argpartition(x, 3)

array([11,  1,  0,  6,  2,  8,  3, 10, 12,  4,  7,  9,  5, 13, 14, 15],
      dtype=int64)

In [102]:
X

array([[5, 2, 4, 8],
       [0, 1, 1, 0],
       [6, 8, 4, 1],
       [1, 8, 0, 7]])

In [103]:
np.argsort(X, axis=1)

array([[1, 2, 0, 3],
       [0, 3, 1, 2],
       [3, 2, 0, 1],
       [2, 0, 3, 1]], dtype=int64)

In [104]:
np.partition(X, 2)

array([[2, 4, 5, 8],
       [0, 0, 1, 1],
       [1, 4, 6, 8],
       [0, 1, 7, 8]])

In [105]:
np.sort(X, 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [106]:
np.sort(X)

array([[2, 4, 5, 8],
       [0, 0, 1, 1],
       [1, 4, 6, 8],
       [0, 1, 7, 8]])