In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [4]:
x.ndim

1

In [5]:
X.ndim

2

In [6]:
X.shape

(3, 5)

In [7]:
X.size

15

In [8]:
x[-1]

9

In [10]:
X[(2,4)]

14

In [11]:
X[2, 4]

14

In [12]:
x[0:5]

array([0, 1, 2, 3, 4])

In [13]:
x[::2]

array([0, 2, 4, 6, 8])

In [14]:
x[::-2]

array([9, 7, 5, 3, 1])

In [15]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [16]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
X[:-2,:-1]

array([[0, 1, 2, 3]])

In [20]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [21]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [22]:
X[0,:]

array([0, 1, 2, 3, 4])

In [23]:
X[1, :]

array([5, 6, 7, 8, 9])

In [25]:
X[:2, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
X[:2, 0]

array([0, 5])

In [28]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
subX[0,0] = 100

In [30]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [31]:
subX2 = X[:2,:3].copy()
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [32]:
subX2[0,0] = 0

In [33]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### Reshape

In [34]:
x.shape

(10,)

In [35]:
x.ndim

1

In [37]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
A = x.reshape(2, 5)

In [41]:
A.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
m = np.arange(24)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
m.reshape(2, 2, -1)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

### 合并与分隔

In [48]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
x
y

array([3, 2, 1])

In [49]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [50]:
z = np.array([666, 6666, 666])

In [52]:
np.concatenate([x, y, z])

array([   1,    2,    3,    3,    2,    1,  666, 6666,  666])

In [53]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [54]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
np.concatenate([A, z.reshape(1, -1)])

array([[   1,    2,    3],
       [   4,    5,    6],
       [ 666, 6666,  666]])

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [59]:
A2

array([[   1,    2,    3],
       [   4,    5,    6],
       [ 666, 6666,  666]])

In [60]:
np.vstack([A, z])

array([[   1,    2,    3],
       [   4,    5,    6],
       [ 666, 6666,  666]])

In [61]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [63]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [64]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### 分隔

In [65]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x1, x2, x3 = np.split(x, [3, 7])

In [67]:
x1

array([0, 1, 2])

In [68]:
x2

array([3, 4, 5, 6])

In [69]:
x3

array([7, 8, 9])

In [70]:
x1, x2 = np.split(x, [5])

In [71]:
x2

array([5, 6, 7, 8, 9])

In [72]:
A = np.full((4, 4), 9)

In [73]:
A

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [74]:
A = np.arange(16).reshape((4, 4))

In [75]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
A1, A2 = np.split(A, [2])

In [77]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
A3, A4 = np.split(A, [2], axis=1)

In [80]:
A3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [81]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [82]:
data = np.arange(16).reshape((4, 4))

In [83]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
X, y = np.hsplit(data, [-1])
y

array([[ 3],
       [ 7],
       [11],
       [15]])

array([[12, 13, 14, 15]])

In [91]:
y[:, -1]

array([ 3,  7, 11, 15])