## 03 numpy.array 基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.15.4'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.15.4'

### Python List的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
import array

In [10]:
arr = array.array('i', [i for i in range(10)])

In [11]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.array

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5]

5

In [16]:
nparr.dtype

dtype('int32')

In [17]:
nparr[5] = 5.1

In [18]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr2 = np.array([1, 2, 3.0])

In [20]:
nparr2.dtype

dtype('float64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(shape=(3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange

In [26]:
[i for i in range(10, 20, 2)]

[10, 12, 14, 16, 18]

In [27]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [28]:
np.arange(10, 20, 0.2)

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2,
       14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4,
       16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6,
       18.8, 19. , 19.2, 19.4, 19.6, 19.8])

In [30]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [31]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [32]:
np.random.randint(0, 10)

7

In [33]:
np.random.randint(0, 10, 10)

array([2, 0, 4, 5, 0, 5, 9, 2, 6, 4])

In [34]:
%time np.random.randint(0, 10, 10)

Wall time: 1e+03 µs


array([9, 3, 3, 1, 5, 6, 3, 0, 6, 2])

In [35]:
np.random.randint(0, 10, size=10)

array([1, 0, 6, 3, 8, 5, 3, 7, 2, 2])

In [36]:
np.random.randint(0, 10, size=(3, 5))

array([[9, 4, 2, 6, 9],
       [2, 4, 5, 4, 7],
       [0, 3, 4, 6, 0]])

In [37]:
np.random.seed(666)

In [38]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [40]:
np.random.seed(666)
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [41]:
np.random.random(10)

array([0.73159555, 0.8578588 , 0.76741234, 0.95323137, 0.29097383,
       0.84778197, 0.3497619 , 0.92389692, 0.29489453, 0.52438061])

In [42]:
np.random.random((3, 5))

array([[0.94253896, 0.07473949, 0.27646251, 0.4675855 , 0.31581532],
       [0.39016259, 0.26832981, 0.75366384, 0.66673747, 0.87287954],
       [0.52109719, 0.75020425, 0.32940234, 0.29130197, 0.00103619]])

In [43]:
np.random.normal((3, 5))

array([3.1121217 , 5.03185388])

In [44]:
np.random.normal(0, 1, size=(3, 5))

array([[-0.19206285,  0.78611284, -1.69046314, -0.98873907,  0.31398563],
       [ 0.39638567,  0.57656584, -0.07019407,  0.91250436,  1.00470497],
       [ 0.41859929, -1.52902454,  0.92487532,  0.18305429,  0.34543496]])

In [47]:
np.random?